### ISSUE TITLE
create bundle with suitable templates

### ISSUE THREAD

**Issue by Der-Achim** [heimrichhannot/contao-search_plus#3]
`mod_search_simple` and `mod_search_advanced` templates do not exist anymore in Contao Version 4. There is only one `mod_search` template which handle both forms. The `mod_search*` templates from Contao Version 3.5 are still working with `contao-search_plus` in Contao Version 4.4

**Comment by winterfox1** [comment]
i want to make a workaround work on my contao 4.4
do i have to simply include the `mod_search*` files to the `/templates` folder?
i tried, but the simple search button has no caption and the form does not lead to search results.

without the files being available there, my contao crashes with an error message.

**Comment by pswerbung** [comment]
Same question here … what do I (exactly) have to do for getting your extension to work in Contao 4.4x – inserting which code into mod_search.html5 and where?

**Comment by koertho** [comment]
For contao 4.x support please check out our [search bundle](https://github.com/heimrichhannot/contao-search-bundle), search_plus will not be actively developed further.
