### ISSUE TITLE
contao-search_plus for contao 4.9+?

### ISSUE THREAD

**Issue by Lelia155** [heimrichhannot/contao-search_plus#4]
Unfortunately, the module does not run under contao 4.9. The pdf-files are not indexed. Are there any plans to adapt the extension?

**Comment by koertho** [comment]
Hi, this bundle is not actively developed anymore, only for some legacy projects. We have a new bundle, called search bundle (https://github.com/heimrichhannot/contao-search-bundle) for new projects, but it has currently no pdf indexing functionality. Maybe we will add it in a future release, but we typical develop features when we need them and pdf indexing wasn't a requested feature in out last projects. I'm sorry!
