### ISSUE TITLE
Module Broken in Contao 4.9

### ISSUE THREAD

**Issue by JessesNei** [heimrichhannot/contao-search_plus#5]
Probably the indexation of PDF files does not work in contao 4.9? 
In frontend there are no search results found and if there is no redirect page there is an fetsch assoc php error.

Thank you for your help!

**Comment by koertho** [comment]
Hi, first of all: Please always provide the contao version, the bundle version and the php version.

Secondly: Have you tried our [Search Bundle](https://github.com/heimrichhannot/contao-search-bundle)? Search_plus is outdated and not actively maintained anymore. The last update was a paid support update.
