### ISSUE TITLE
Security issues with haste_plus

### ISSUE THREAD

**Issue by rustykowski** [heimrichhannot/contao-search_plus#6]
**Context**
Contao version: 4.9.34
Bundle version: 1.2.0
PHP version: 7.4.22

**Description**
contao-search_plus requires heimrichhannot/contao-haste_plus, which requires "phpfastcache/phpfastcache": "^5.0"
This installs phpfastcache in Version 5.0.21 in my environment. The newest Version of phpfastcache is 9.1.2.
Phpfastcache 5.0.21 has [this security issue](https://github.com/advisories/GHSA-cvh5-p6r6-g2qc).

Could that be resolved bei updating the requirement constraints?

**Comment by koertho** [comment]
Hi, thanks for reporting. The issue with haste_plus and phpfastcache are already on my agenda. 
In your case I recommend to upgrade to our [Search Bundle](https://github.com/heimrichhannot/contao-search-bundle). It's build for contao 4. Search_plus is not maintained anymore, as you can read in the readme.

**Comment by rustykowski** [comment]
fantastic, thank you!

**Comment by koertho** [comment]
Haste_plus now allows phpfastcache v6. Newer is not possible due namespace changes. But I hardly recommend switching to search bundle (or something other replaces the functionality you need).
